dependencies {
    testImplementation project(':gateway')
    testImplementation project(':connector-spi')
    testImplementation project(':connector-openapi')
    testImplementation project(':connector-sql')
    testImplementation project(':example-connector-echo')
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'com.tngtech.archunit:archunit-junit5:1.4.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
