# Usage:
#   docker compose -f docker-compose.yml -f docker-compose.jwt.yml up -d --wait --force-recreate --no-deps gateway
services:
  gateway:
    environment:
      SPRING_PROFILES_ACTIVE: docker,jwt
