plugins {
    id 'java-library'
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.12.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.assertj:assertj-core:3.27.3'
    testImplementation "com.tngtech.archunit:archunit-junit5:${archunitVersion}"
}
